// src/components/ConversionPages/BaseConverter.tsx
import React, { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Upload, Download, RefreshCw, ArrowLeft, CheckCircle, AlertCircle, Star } from 'lucide-react';
import { Header } from '../Header';
import { Footer } from '../Footer';

interface BaseConverterProps {
  title: string;
  description: string;
  inputFormat: string;
  outputFormat: string;
  inputExtensions: string[];
  outputExtensions: string[];
  onConvert: (file: File) => Promise<Blob>;
  seoTitle: string;
  seoDescription: string;
  features: string[];
  useCases: string[];
}


export const BaseConverter: React.FC<BaseConverterProps> = ({
  title,
  description,
  inputFormat,
  outputFormat,
  inputExtensions,
  outputExtensions,
  onConvert,
  seoTitle,
  seoDescription,
  features,
  useCases
}) => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [convertedFile, setConvertedFile] = useState<Blob | null>(null);
  const [isConverting, setIsConverting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setSelectedFile(file);
      setError(null);
      setConvertedFile(null);
    }
  };

  const handleConvert = async () => {
    if (!selectedFile) return;


    setIsConverting(true);
    setError(null);

    try {
      const result = await onConvert(selectedFile);
      setConvertedFile(result);
      
      // Record conversion for anonymous users
      if (!user) {
        ConversionLimits.recordConversion();
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Conversion failed');
    } finally {
      setIsConverting(false);
    }
  };

  const handleDownload = () => {
    if (!convertedFile) return;

    const url = URL.createObjectURL(convertedFile);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedFile?.name.split('.')[0] || 'converted'}.${outputFormat.toLowerCase()}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleBack = () => {
    // Always go to home page for consistency
    window.location.href = '/';
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Helmet>
        <title>{seoTitle}</title>
        <meta name="description" content={seoDescription} />
        <meta property="og:title" content={seoTitle} />
        <meta property="og:description" content={seoDescription} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={window.location.href} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={seoTitle} />
        <meta name="twitter:description" content={seoDescription} />
      </Helmet>
      
      <Header />
      
      {/* Back Button */}
      <div className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="py-4">
            <button
              onClick={handleBack}
              className="flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
              <span>Back to Home</span>
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Converter */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-lg p-8">
              <div className="text-center mb-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-4">
                  Convert {inputFormat.toUpperCase()} to {outputFormat.toUpperCase()}
                </h2>
                <p className="text-lg text-gray-600">{description}</p>
              </div>

              {/* File Upload */}
              <div className="mb-8">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Select {inputFormat.toUpperCase()} File
                </label>
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-blue-400 transition-colors">
                  <input
                    type="file"
                    accept={inputExtensions.map(ext => `.${ext}`).join(',')}
                    onChange={handleFileSelect}
                    className="hidden"
                    id="file-upload"
                  />
                  <label
                    htmlFor="file-upload"
                    className="cursor-pointer flex flex-col items-center space-y-4"
                  >
                    <Upload className="w-12 h-12 text-gray-400" />
                    <div>
                      <p className="text-lg font-medium text-gray-900">
                        Click to upload or drag and drop
                      </p>
                      <p className="text-sm text-gray-500">
                        {inputExtensions.map(ext => `.${ext}`).join(', ')} files
                      </p>
                    </div>
                  </label>
                </div>
                {selectedFile && (
                  <div className="mt-4 p-4 bg-blue-50 rounded-lg">
                    <p className="text-sm text-blue-800">
                      Selected: {selectedFile.name} ({(selectedFile.size / 1024 / 1024).toFixed(2)} MB)
                    </p>
                  </div>
                )}
              </div>

              {/* Convert Button */}
              <div className="text-center mb-8">
                <button
                  onClick={handleConvert}
                  disabled={!selectedFile || isConverting}
                  className="bg-blue-600 text-white px-8 py-3 rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center space-x-2 mx-auto"
                >
                  {isConverting ? (
                    <>
                      <RefreshCw className="w-5 h-5 animate-spin" />
                      <span>Converting...</span>
                    </>
                  ) : (
                    <>
                      <RefreshCw className="w-5 h-5" />
                      <span>Convert to {outputFormat.toUpperCase()}</span>
                    </>
                  )}
                </button>
              </div>

              {/* Error Display */}
              {error && (
                <div className="mb-8 p-4 bg-red-50 border border-red-200 rounded-lg flex items-center space-x-2">
                  <AlertCircle className="w-5 h-5 text-red-500" />
                  <p className="text-red-700">{error}</p>
                </div>
              )}

              {/* Download Button */}
              {convertedFile && (
                <div className="text-center">
                  <div className="mb-4 p-4 bg-green-50 border border-green-200 rounded-lg flex items-center justify-center space-x-2">
                    <CheckCircle className="w-5 h-5 text-green-500" />
                    <p className="text-green-700 font-medium">Conversion completed successfully!</p>
                  </div>
                  <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                    <button
                      onClick={handleDownload}
                      className="bg-green-600 text-white px-8 py-3 rounded-lg font-medium hover:bg-green-700 transition-colors flex items-center space-x-2"
                    >
                      <Download className="w-5 h-5" />
                      <span>Download {outputFormat.toUpperCase()}</span>
                    </button>
                    <button
                      onClick={() => {
                        setSelectedFile(null);
                        setConvertedFile(null);
                        setError(null);
                        // Reset file input
                        const fileInput = document.getElementById('file-upload') as HTMLInputElement;
                        if (fileInput) fileInput.value = '';
                      }}
                      className="bg-blue-600 text-white px-8 py-3 rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center space-x-2"
                    >
                      <RefreshCw className="w-5 h-5" />
                      <span>Convert Another File</span>
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Features */}
            <div className="bg-white rounded-2xl shadow-lg p-6">
              <h3 className="text-lg font-bold text-gray-900 mb-4">Key Features</h3>
              <ul className="space-y-2">
                {features.map((feature, index) => (
                  <li key={index} className="flex items-start space-x-2">
                    <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-gray-600">{feature}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Use Cases */}
            <div className="bg-white rounded-2xl shadow-lg p-6">
              <h3 className="text-lg font-bold text-gray-900 mb-4">Common Use Cases</h3>
              <ul className="space-y-2">
                {useCases.map((useCase, index) => (
                  <li key={index} className="flex items-start space-x-2">
                    <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0" />
                    <span className="text-sm text-gray-600">{useCase}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Format Info */}
            <div className="bg-white rounded-2xl shadow-lg p-6">
              <h3 className="text-lg font-bold text-gray-900 mb-4">Format Information</h3>
              <div className="space-y-3">
                <div>
                  <p className="text-sm font-medium text-gray-700">Input Format</p>
                  <p className="text-sm text-gray-600">{inputFormat.toUpperCase()}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-700">Output Format</p>
                  <p className="text-sm text-gray-600">{outputFormat.toUpperCase()}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-700">Supported Extensions</p>
                  <p className="text-sm text-gray-600">
                    {inputExtensions.map(ext => `.${ext}`).join(', ')}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <Footer />

    </div>
  );
};

// src/components/BaseConverter.qwik.tsx
import { component$, useSignal, $, type QRL } from '@builder.io/qwik';
import { Upload, Download, RefreshCw, ArrowLeft, CheckCircle, AlertCircle } from 'lucide-react';

interface BaseConverterProps {
  title: string;
  description: string;
  inputFormat: string;
  outputFormat: string;
  inputExtensions: string[];
  outputExtensions: string[];
  onConvert: QRL<(file: File) => Promise<Blob>>;
  features: string[];
  useCases: string[];
}

export const BaseConverter = component$<BaseConverterProps>(({
  title,
  description,
  inputFormat,
  outputFormat,
  inputExtensions,
  outputExtensions,
  onConvert,
  features,
  useCases
}) => {
  const selectedFile = useSignal<File | null>(null);
  const convertedFile = useSignal<Blob | null>(null);
  const isConverting = useSignal(false);
  const error = useSignal<string | null>(null);

  const handleFileSelect = $((event: Event) => {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      selectedFile.value = file;
      error.value = null;
      convertedFile.value = null;
    }
  });

  const handleConvert = $(async () => {
    if (!selectedFile.value) return;

    isConverting.value = true;
    error.value = null;

    try {
      const result = await onConvert(selectedFile.value);
      convertedFile.value = result;
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Conversion failed';
    } finally {
      isConverting.value = false;
    }
  });

  const handleDownload = $(() => {
    if (!convertedFile.value) return;

    const url = URL.createObjectURL(convertedFile.value);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedFile.value?.name.split('.')[0] || 'converted'}.${outputFormat.toLowerCase()}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });

  return (
    <div class="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div class="mb-8">
          <a href="/" class="inline-flex items-center text-blue-600 hover:text-blue-700 mb-4">
            <ArrowLeft class="w-5 h-5 mr-2" />
            Back to Home
          </a>
          <h1 class="text-4xl font-bold text-gray-900 mb-4">{title}</h1>
          <p class="text-lg text-gray-600">{description}</p>
        </div>

        {/* Converter Card */}
        <div class="bg-white rounded-2xl shadow-xl p-8 mb-8">
          {/* File Upload */}
          {!selectedFile.value && (
            <div class="border-3 border-dashed border-gray-300 rounded-xl p-12 text-center hover:border-blue-400 transition-colors">
              <Upload class="w-16 h-16 mx-auto text-gray-400 mb-4" />
              <p class="text-lg font-semibold text-gray-700 mb-2">
                Drop your {inputFormat} file here
              </p>
              <p class="text-sm text-gray-500 mb-4">
                or click to browse
              </p>
              <input
                type="file"
                accept={inputExtensions.map(ext => `.${ext}`).join(',')}
                onChange$={handleFileSelect}
                class="hidden"
                id="file-upload"
              />
              <label
                for="file-upload"
                class="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 cursor-pointer transition-colors"
              >
                Select File
              </label>
            </div>
          )}

          {/* Selected File */}
          {selectedFile.value && !convertedFile.value && (
            <div class="space-y-6">
              <div class="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                <div class="flex items-center space-x-3">
                  <CheckCircle class="w-6 h-6 text-green-500" />
                  <div>
                    <p class="font-semibold text-gray-900">{selectedFile.value.name}</p>
                    <p class="text-sm text-gray-500">
                      {(selectedFile.value.size / 1024).toFixed(2)} KB
                    </p>
                  </div>
                </div>
                <button
                  onClick$={() => selectedFile.value = null}
                  class="text-red-600 hover:text-red-700 text-sm font-medium"
                >
                  Remove
                </button>
              </div>

              <button
                onClick$={handleConvert}
                disabled={isConverting.value}
                class="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg font-semibold hover:from-blue-700 hover:to-purple-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2"
              >
                {isConverting.value ? (
                  <>
                    <RefreshCw class="w-5 h-5 animate-spin" />
                    <span>Converting...</span>
                  </>
                ) : (
                  <>
                    <RefreshCw class="w-5 h-5" />
                    <span>Convert to {outputFormat}</span>
                  </>
                )}
              </button>
            </div>
          )}

          {/* Error */}
          {error.value && (
            <div class="flex items-center space-x-3 p-4 bg-red-50 rounded-lg border border-red-200">
              <AlertCircle class="w-6 h-6 text-red-500 flex-shrink-0" />
              <p class="text-red-700">{error.value}</p>
            </div>
          )}

          {/* Success */}
          {convertedFile.value && (
            <div class="space-y-6">
              <div class="flex items-center justify-center p-8 bg-green-50 rounded-lg border border-green-200">
                <CheckCircle class="w-12 h-12 text-green-500 mr-4" />
                <div>
                  <p class="text-lg font-semibold text-gray-900">Conversion Complete!</p>
                  <p class="text-sm text-gray-600">Your file is ready to download</p>
                </div>
              </div>

              <button
                onClick$={handleDownload}
                class="w-full py-4 bg-gradient-to-r from-green-600 to-teal-600 text-white rounded-lg font-semibold hover:from-green-700 hover:to-teal-700 transition-all shadow-lg hover:shadow-xl flex items-center justify-center space-x-2"
              >
                <Download class="w-5 h-5" />
                <span>Download {outputFormat}</span>
              </button>

              <button
                onClick$={() => {
                  selectedFile.value = null;
                  convertedFile.value = null;
                }}
                class="w-full py-3 text-gray-600 hover:text-gray-900 font-medium"
              >
                Convert Another File
              </button>
            </div>
          )}
        </div>

        {/* Features */}
        <div class="grid md:grid-cols-2 gap-8">
          <div class="bg-white rounded-xl shadow-lg p-6">
            <h2 class="text-xl font-bold text-gray-900 mb-4">Features</h2>
            <ul class="space-y-3">
              {features.map((feature, idx) => (
                <li key={idx} class="flex items-start space-x-2">
                  <CheckCircle class="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                  <span class="text-gray-700">{feature}</span>
                </li>
              ))}
            </ul>
          </div>

          <div class="bg-white rounded-xl shadow-lg p-6">
            <h2 class="text-xl font-bold text-gray-900 mb-4">Use Cases</h2>
            <ul class="space-y-3">
              {useCases.map((useCase, idx) => (
                <li key={idx} class="flex items-start space-x-2">
                  <CheckCircle class="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
                  <span class="text-gray-700">{useCase}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
});
